### PR TITLE
Add .f postfix to version number

### PR DESCRIPTION
**Pull request by xavery**

### CODE REVIEW

**Comment by fredo-47** [comment]
Nice one!

Could you also make use of the [original built.sh script](https://github.com/transmission-remote-gui/transgui/blob/master/setup/unix/build.sh) features, which modify the `about.lfm` file so the `Help/About` dialog box will show the actual transgui Build version, as well as the actual FPC and Lazarus versions used?

**Comment by xavery** [comment]
@fredo-47 The stuff in the original `build.sh` is not needed since the application version is now taken from inside the binary itself (thanks to the changes here), while FPC and Lazarus version are filled-in automatically at compile time via `FPCVERSION` and `lcl_version` :

```pascal
txVersion.Caption:=Format(txVersion.Caption, [AppVersion]);
txVersFPC.caption := 'Fpc : ' + {$I %FPCVERSION%} + '   Lazarus : ' +lcl_version;
```

**Comment by fredo-47** [comment]
Alright, but the AppVersion means `5.18.0`, or in your latest one `5.18.0.f`, right?

The About window with your transgui:
transgui-xavery

The About window with original transgui:
transgui

I find it helpful that it has the Build number in it too, in order to identify the exact code/version that it was built from.
Just a suggestion from my side :-)

I understand it comes from this line in the original script:
`build="$(git rev-list --abbrev-commit --max-count=1 HEAD)"`

**Comment by xavery** [comment]
Sure, why not. I'll add that in.

**Pull request merged**
